// Werdy Hukuk Bürosu — ekip verileri

// Pozisyon sıralaması (yukarıdan aşağıya)
export const POSITIONS = [
  { id: 'partner', tr: 'Ana Konuşmacı', en: 'Keynote Speaker' },
  { id: 'associate', tr: 'Panelist', en: 'Panelist' },
  { id: 'trainee', tr: 'Atölye Lideri', en: 'Workshop Leader' },
];

// Çalışma alanları (filtre için)
export const PRACTICE_AREAS = [
  { id: 'ux', tr: 'Kullanıcı Deneyimi (UX/UI)', en: 'User Experience (UX/UI)' },
  { id: 'branding', tr: 'Marka Kimliği & Branding', en: 'Brand Identity & Branding' },
  { id: 'ai', tr: 'Yapay Zeka & Sanat', en: 'AI & Art' },
  { id: 'web3', tr: 'Web3 & Gelecek Teknolojileri', en: 'Web3 & Future Tech' },
  { id: 'leadership', tr: 'Yaratıcı Liderlik', en: 'Creative Leadership' },
  { id: 'strategy', tr: 'Kreatif Strateji', en: 'Creative Strategy' },
  { id: 'motion', tr: 'Motion & Hareketli Grafik', en: 'Motion & Motion Graphics' },
  { id: 'dev', tr: 'Yazılım & Teknolojik Arayüzler', en: 'Software & Tech Interfaces' },
  { id: 'content', tr: 'İçerik Stratejisi', en: 'Content Strategy' },
];

export const teamMembers = [
  {
    id: 184,
    slug: 'caner-demir',
    name: 'Caner Demir',
    position: 'partner',
    titleEn: 'Keynote Speaker',
    titleTr: 'Ana Konuşmacı',
    email: 'cdemir@redmono.com',
    phone: '+90 212 900 00 00',
    image: '/assets/team/redmono-avatar.svg',
    practiceAreas: ['ux', 'branding', 'ai', 'leadership'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'Boston University School of Design, MFA (1989)',
      'Dokuz Eylül Üniversitesi Tasarım Bölümü, BFA (1985)',
      'Merrill High School, Wisconsin (1980)',
    ],
    bar: 'Redmono Design Collective',
  },
  {
    id: 205,
    slug: 'ayse-yilmaz',
    name: 'Ayşe Yılmaz',
    position: 'partner',
    titleEn: 'Keynote Speaker',
    titleTr: 'Ana Konuşmacı',
    email: 'ayilmaz@redmono.com',
    phone: '+90 212 900 00 00',
    image: '/assets/team/redmono-avatar.svg',
    practiceAreas: ['leadership', 'strategy', 'dev', 'content'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'İstanbul Üniversitesi, Sosyoloji (2018)',
      'İzmir Dokuz Eylül Üniversitesi Tasarım Bölümü, BFA (1996)',
      'TED Lisesi, Zonguldak (1990)',
    ],
    bar: 'Redmono Design Collective',
  },
  {
    id: 215,
    slug: 'murat-kaya',
    name: 'Murat Kaya',
    position: 'partner',
    titleEn: 'Keynote Speaker',
    titleTr: 'Ana Konuşmacı',
    email: 'mkaya@redmono.com',
    phone: '+90 212 900 00 00',
    image: '/assets/team/redmono-avatar.svg',
    practiceAreas: ['ux', 'web3'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'İstanbul Üniversitesi Tasarım Bölümü, BFA (2003)',
      'Anadolu Lisesi, Bursa (1999)',
    ],
    bar: 'Redmono Design Collective',
  },
  {
    id: 1240,
    slug: 'zeynep-celik',
    name: 'Zeynep Çelik',
    position: 'partner',
    titleEn: 'Keynote Speaker',
    titleTr: 'Ana Konuşmacı',
    email: 'zcelik@redmono.com',
    phone: '+90 212 900 00 00',
    image: '/assets/team/redmono-avatar.svg',
    practiceAreas: ['branding', 'ai', 'web3', 'leadership', 'strategy', 'motion'],
    languages: ['Türkçe', 'İngilizce', 'Hollandaca', 'Almanca'],
    education: [
      'İstanbul Üniversitesi, Etkileşim Tasarımı Doktora Adayı (2018)',
      'University of Cambridge, MFA (2017)',
      'Bilkent Üniversitesi, BFA (2016)',
      'TED Ankara Koleji (2012)',
      'Jan Arentsz CSG, Hollanda (2011)',
    ],
    bar: 'Redmono Design Collective',
  },
  {
    id: 1287,
    slug: 'bora-arslan',
    name: 'Bora Arslan',
    position: 'associate',
    titleEn: 'Panelist',
    titleTr: 'Panelist',
    email: 'barslan@redmono.com',
    phone: '+90 212 900 00 00',
    image: '/assets/team/redmono-avatar.svg',
    practiceAreas: ['ux', 'branding', 'web3'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'Marmara Üniversitesi Tasarım Bölümü, BFA (2021)',
      'Enka Okulları, Adapazarı (2016)',
    ],
    bar: 'Redmono Design Collective',
  },
  {
    id: 1295,
    slug: 'elif-yildiz',
    name: 'Elif Yıldız',
    position: 'associate',
    titleEn: 'Panelist',
    titleTr: 'Panelist',
    email: 'eyildiz@redmono.com',
    phone: '+90 212 900 00 00',
    image: '/assets/team/redmono-avatar.svg',
    practiceAreas: ['leadership', 'dev'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'TOBB Ekonomi ve Teknoloji Üniversitesi Tasarım Bölümü, BFA (2022)',
      'Karabük Anadolu Öğretmen Lisesi (2017)',
    ],
    bar: 'Redmono Design Collective',
  },
  {
    id: 1308,
    slug: 'deniz-ozturk',
    name: 'Deniz Öztürk',
    position: 'associate',
    titleEn: 'Panelist',
    titleTr: 'Panelist',
    email: 'dozturk@redmono.com',
    phone: '+90 212 900 00 00',
    image: '/assets/team/redmono-avatar.svg',
    practiceAreas: ['ux', 'branding', 'web3'],
    languages: ['İngilizce', 'Almanca', 'Türkçe'],
    education: [
      'İstanbul Bilgi Üniversitesi Tasarım Bölümü, BFA (2023)',
      'Cağaloğlu Anadolu Lisesi (2018)',
    ],
    bar: 'Redmono Design Collective',
  },
  {
    id: 1309,
    slug: 'merve-bulut',
    name: 'Merve Bulut',
    position: 'associate',
    titleEn: 'Panelist',
    titleTr: 'Panelist',
    email: 'mbulut@redmono.com',
    phone: '+90 212 900 00 00',
    image: '/assets/team/redmono-avatar.svg',
    practiceAreas: ['ux', 'branding', 'web3'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'Koç Üniversitesi Tasarım Bölümü, BFA (2022)',
      'Tarsus Amerikan Koleji (2017)',
    ],
    bar: 'Redmono Design Collective',
  },
  {
    id: 1310,
    slug: 'kaan-koc',
    name: 'Kaan Koç',
    position: 'associate',
    titleEn: 'Panelist',
    titleTr: 'Panelist',
    email: 'kkoc@redmono.com',
    phone: '+90 212 900 00 00',
    image: '/assets/team/redmono-avatar.svg',
    practiceAreas: ['ux', 'branding', 'web3'],
    languages: ['Türkçe', 'Almanca', 'İngilizce'],
    education: [
      'Türk-Alman Üniversitesi Tasarım Bölümü, BFA (2024)',
      'Çemberlitaş Anadolu Lisesi (2017)',
    ],
    bar: 'Redmono Design Collective',
  },
  {
    id: 1311,
    slug: 'selin-aydin',
    name: 'Selin Aydın',
    position: 'trainee',
    titleEn: 'Workshop Leader',
    titleTr: 'Atölye Lideri',
    email: 'saydin@redmono.com',
    phone: '+90 212 900 00 00',
    image: '/assets/team/redmono-avatar.svg',
    practiceAreas: ['ux', 'branding', 'web3'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'TOBB Ekonomi ve Teknoloji Üniversitesi Tasarım Bölümü, BFA (Beklenen 2026)',
      'TOBB Anadolu Lisesi (2018)',
    ],
    bar: null,
  },
  {
    id: 1313,
    slug: 'burak-guler',
    name: 'Burak Güler',
    position: 'trainee',
    titleEn: 'Workshop Leader',
    titleTr: 'Atölye Lideri',
    email: 'bguler@redmono.com',
    phone: '+90 212 900 00 00',
    image: '/assets/team/redmono-avatar.svg',
    practiceAreas: ['ux', 'branding', 'web3'],
    languages: ['Türkçe', 'İngilizce', 'Almanca'],
    education: [
      'Koç Üniversitesi Tasarım Bölümü, BFA (2025)',
      'Tarsus Amerikan Koleji (2021)',
      'SEV Tarsus (2016)',
    ],
    bar: null,
  },
  {
    id: 1317,
    slug: 'irem-cetin',
    name: 'İrem Çetin',
    position: 'trainee',
    titleEn: 'Workshop Leader',
    titleTr: 'Atölye Lideri',
    email: 'icetin@redmono.com',
    phone: '+90 212 900 00 00',
    image: '/assets/team/redmono-avatar.svg',
    practiceAreas: ['ux', 'branding', 'web3'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'İstanbul Üniversitesi, BFA (2024)',
      'TED Koleji, Kayseri (2020)',
    ],
    bar: null,
  },
  {
    id: 1318,
    slug: 'mete-aksoy',
    name: 'Mete Aksoy',
    position: 'trainee',
    titleEn: 'Workshop Leader',
    titleTr: 'Atölye Lideri',
    email: 'maksoy@redmono.com',
    phone: '+90 212 900 00 00',
    image: '/assets/team/redmono-avatar.svg',
    practiceAreas: ['leadership', 'dev'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'Özyeğin Üniversitesi Tasarım Bölümü, BFA (Beklenen 2025)',
      'Elazığ Final Akademi Lisesi (2021)',
    ],
    bar: null,
  },
  {
    id: 1319,
    slug: 'asli-yavuz',
    name: 'Aslı Yavuz',
    position: 'trainee',
    titleEn: 'Workshop Leader',
    titleTr: 'Atölye Lideri',
    email: 'ayavuz@redmono.com',
    phone: '+90 212 900 00 00',
    image: '/assets/team/redmono-avatar.svg',
    practiceAreas: ['ux', 'branding', 'web3'],
    languages: ['Türkçe', 'İngilizce', 'Arapça'],
    education: [
      'Koç Üniversitesi Tasarım Bölümü, BFA (2025)',
      'Tarsus Amerikan Koleji (2021)',
    ],
    bar: null,
  }
];
