// Werdy Hukuk Bürosu — ekip verileri (werdy.av.tr'den alınmıştır)

const IMG_BASE = 'https://werdy.av.tr';

// Pozisyon sıralaması (yukarıdan aşağıya)
export const POSITIONS = [
  { id: 'partner', tr: 'Ortak', en: 'Partner' },
  { id: 'associate', tr: 'Avukat', en: 'Associate' },
  { id: 'trainee', tr: 'Stajyer Avukat', en: 'Trainee' },
];

// Çalışma alanları (filtre için)
export const PRACTICE_AREAS = [
  { id: 'banking', tr: 'Bankacılık ve Finansal Hizmetler', en: 'Banking & Financial Services' },
  { id: 'ma', tr: 'Birleşme ve Devralma / Şirketler', en: 'M&A & Corporate' },
  { id: 'privatization', tr: 'Özelleştirme', en: 'Privatization' },
  { id: 'capital-markets', tr: 'Sermaye Piyasaları', en: 'Capital Markets' },
  { id: 'dispute', tr: 'Uyuşmazlık Çözümü', en: 'Dispute Resolution' },
  { id: 'competition', tr: 'Rekabet Hukuku', en: 'Competition' },
  { id: 'foreign-investment', tr: 'Yabancı Yatırım', en: 'Foreign Investment' },
  { id: 'ip', tr: 'Fikri Mülkiyet', en: 'Intellectual Property' },
  { id: 'it', tr: 'BT / İletişim', en: 'IT / Communications' },
];

export const teamMembers = [
{
    id: 184,
    slug: 'a-can-werdy',
    name: 'A. Can Werdy',
    position: 'partner',
    titleEn: 'Partner',
    titleTr: 'Ortak',
    email: 'cwerdy@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: '/assets/team/a-can-werdy.png',
    practiceAreas: ['banking', 'ma', 'privatization', 'dispute'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'Boston University School of Law, LL.M. (1989)',
      'Dokuz Eylül Üniversitesi Hukuk Fakültesi, LL.B. (1985)',
      'Merrill High School, Wisconsin (1980)',
    ],
    bar: 'İstanbul Barosu',
  },
{
    id: 205,
    slug: 'ozer-koseoglu',
    name: 'Özer Köseoğlu',
    position: 'partner',
    titleEn: 'Partner',
    titleTr: 'Ortak',
    email: 'okoseoglu@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: '/assets/team/ozer-koseoglu.png',
    practiceAreas: ['dispute', 'competition', 'ip', 'it'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'İstanbul Üniversitesi, Sosyoloji (2018)',
      'İzmir Dokuz Eylül Üniversitesi Hukuk Fakültesi, LL.B. (1996)',
      'TED Lisesi, Zonguldak (1990)',
    ],
    bar: 'İstanbul Barosu',
  },
{
    id: 215,
    slug: 'zeynep-fencimen',
    name: 'Zeynep Fencimen',
    position: 'partner',
    titleEn: 'Partner',
    titleTr: 'Ortak',
    email: 'zfencimen@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: '/assets/team/zeynep-fencimen.png',
    practiceAreas: ['banking', 'capital-markets'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'İstanbul Üniversitesi Hukuk Fakültesi, LL.B. (2003)',
      'Anadolu Lisesi, Bursa (1999)',
    ],
    bar: 'İstanbul Barosu',
  },
{
    id: 1240,
    slug: 'dogac-gunaydin',
    name: 'Doğaç Günaydın',
    position: 'partner',
    titleEn: 'Partner',
    titleTr: 'Ortak',
    email: 'dgunaydin@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: '/assets/team/dogac-gunaydin.png',
    practiceAreas: ['ma', 'privatization', 'capital-markets', 'dispute', 'competition', 'foreign-investment'],
    languages: ['Türkçe', 'İngilizce', 'Hollandaca', 'Almanca'],
    education: [
      'İstanbul Üniversitesi, Özel Hukuk Doktora Adayı (2018)',
      'University of Cambridge, LL.M. (2017)',
      'Bilkent Üniversitesi, LL.B. (2016)',
      'TED Ankara Koleji (2012)',
      'Jan Arentsz CSG, Hollanda (2011)',
    ],
    bar: 'İstanbul Barosu',
  },
{
    id: 1287,
    slug: 'yaren-kinalioglu',
    name: 'Yaren Kınalıoğlu',
    position: 'associate',
    titleEn: 'Associate',
    titleTr: 'Avukat',
    email: 'ykinalioglu@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: '/assets/team/yaren-kinalioglu.png',
    practiceAreas: ['banking', 'ma', 'capital-markets'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'Marmara Üniversitesi Hukuk Fakültesi, LL.B. (2021)',
      'Enka Okulları, Adapazarı (2016)',
    ],
    bar: 'İstanbul Barosu',
  },
{
    id: 1295,
    slug: 'beyda-ulu',
    name: 'Beyda Ulu',
    position: 'associate',
    titleEn: 'Associate',
    titleTr: 'Avukat',
    email: 'bulu@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: '/assets/team/beyda-ulu.png',
    practiceAreas: ['dispute', 'ip'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'TOBB Ekonomi ve Teknoloji Üniversitesi Hukuk Fakültesi, LL.B. (2022)',
      'Karabük Anadolu Öğretmen Lisesi (2017)',
    ],
    bar: 'İstanbul Barosu',
  },
{
    id: 1308,
    slug: 'alparslan-erbay',
    name: 'Alparslan Erbay',
    position: 'associate',
    titleEn: 'Associate',
    titleTr: 'Avukat',
    email: 'aerbay@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: '/assets/team/alparslan-erbay.png',
    practiceAreas: ['banking', 'ma', 'capital-markets'],
    languages: ['İngilizce', 'Almanca', 'Türkçe'],
    education: [
      'İstanbul Bilgi Üniversitesi Hukuk Fakültesi, LL.B. (2023)',
      'Cağaloğlu Anadolu Lisesi (2018)',
    ],
    bar: 'İstanbul Barosu',
  },
{
    id: 1309,
    slug: 'pelin-nida-surmeli',
    name: 'Pelin Nida Sürmeli',
    position: 'associate',
    titleEn: 'Associate',
    titleTr: 'Avukat',
    email: 'psurmeli@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: '/assets/team/pelin-nida-surmeli.png',
    practiceAreas: ['banking', 'ma', 'capital-markets'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'Koç Üniversitesi Hukuk Fakültesi, LL.B. (2022)',
      'Tarsus Amerikan Koleji (2017)',
    ],
    bar: 'İstanbul Barosu',
  },
{
    id: 1310,
    slug: 'taylan-ozgur-kocak',
    name: 'Taylan Özgür Koçak',
    position: 'associate',
    titleEn: 'Associate',
    titleTr: 'Avukat',
    email: 'tkocak@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: '/assets/team/taylan-ozgur-kocak.png',
    practiceAreas: ['banking', 'ma', 'capital-markets'],
    languages: ['Türkçe', 'Almanca', 'İngilizce'],
    education: [
      'Türk-Alman Üniversitesi Hukuk Fakültesi, LL.B. (2024)',
      'Çemberlitaş Anadolu Lisesi (2017)',
    ],
    bar: 'İstanbul Barosu',
  },
{
    id: 1311,
    slug: 'selin-tutucu',
    name: 'Selin Tutucu',
    position: 'trainee',
    titleEn: 'Trainee',
    titleTr: 'Stajyer Avukat',
    email: 'stutucu@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: '/assets/team/selin-tutucu.png',
    practiceAreas: ['banking', 'ma', 'capital-markets'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'TOBB Ekonomi ve Teknoloji Üniversitesi Hukuk Fakültesi, LL.B. (Beklenen 2026)',
      'TOBB Anadolu Lisesi (2018)',
    ],
    bar: null,
  },
{
    id: 1313,
    slug: 'can-berk-kahya',
    name: 'Can Berk Kahya',
    position: 'trainee',
    titleEn: 'Trainee',
    titleTr: 'Stajyer Avukat',
    email: 'ckahya@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: '/assets/team/can-berk-kahya.png',
    practiceAreas: ['banking', 'ma', 'capital-markets'],
    languages: ['Türkçe', 'İngilizce', 'Almanca'],
    education: [
      'Koç Üniversitesi Hukuk Fakültesi, LL.B. (2025)',
      'Tarsus Amerikan Koleji (2021)',
      'SEV Tarsus (2016)',
    ],
    bar: null,
  },
{
    id: 1317,
    slug: 'ilayda-kizikli',
    name: 'İlayda Kızıklı',
    position: 'trainee',
    titleEn: 'Trainee',
    titleTr: 'Stajyer Avukat',
    email: 'ikizikli@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: '/assets/team/ilayda-kizikli.png',
    practiceAreas: ['banking', 'ma', 'capital-markets'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'İstanbul Üniversitesi, LL.B. (2024)',
      'TED Koleji, Kayseri (2020)',
    ],
    bar: null,
  },
{
    id: 1318,
    slug: 'metehan-unal',
    name: 'Metehan Ünal',
    position: 'trainee',
    titleEn: 'Trainee',
    titleTr: 'Stajyer Avukat',
    email: 'munal@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: '/assets/team/metehan-unal.png',
    practiceAreas: ['dispute', 'ip'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'Özyeğin Üniversitesi Hukuk Fakültesi, LL.B. (Beklenen 2025)',
      'Elazığ Final Akademi Lisesi (2021)',
    ],
    bar: null,
  },
  {
    id: 1319,
    slug: 'aksel-kalaycioglu',
    name: 'Aksel Kalaycıoğlu',
    position: 'trainee',
    titleEn: 'Trainee',
    titleTr: 'Stajyer Avukat',
    email: 'akalaycioglu@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: '/assets/team/aksel-kalaycioglu.png',
    practiceAreas: ['banking', 'ma', 'capital-markets'],
    languages: ['Türkçe', 'İngilizce', 'Arapça'],
    education: [
      'Koç Üniversitesi Hukuk Fakültesi, LL.B. (2025)',
      'Tarsus Amerikan Koleji (2021)',
    ],
    bar: null,
  }
];
