// Werdy Hukuk Bürosu — ekip verileri

// Pozisyon sıralaması (yukarıdan aşağıya)
export const POSITIONS = [
  { id: 'partner', tr: 'Ortak', en: 'Partner' },
  { id: 'associate', tr: 'Avukat', en: 'Associate' },
  { id: 'trainee', tr: 'Stajyer Avukat', en: 'Trainee' },
];

// Çalışma alanları (filtre için)
export const PRACTICE_AREAS = [
  { id: 'banking', tr: 'Bankacılık ve Finansal Hizmetler', en: 'Banking & Financial Services' },
  { id: 'ma', tr: 'Birleşme ve Devralma / Şirketler', en: 'M&A & Corporate' },
  { id: 'privatization', tr: 'Özelleştirme', en: 'Privatization' },
  { id: 'capital-markets', tr: 'Sermaye Piyasaları', en: 'Capital Markets' },
  { id: 'dispute', tr: 'Uyuşmazlık Çözümü', en: 'Dispute Resolution' },
  { id: 'competition', tr: 'Rekabet Hukuku', en: 'Competition' },
  { id: 'foreign-investment', tr: 'Yabancı Yatırım', en: 'Foreign Investment' },
  { id: 'ip', tr: 'Fikri Mülkiyet', en: 'Intellectual Property' },
  { id: 'it', tr: 'BT / İletişim', en: 'IT / Communications' },
];

export const teamMembers = [
  {
    id: 184,
    slug: 'caner-demir',
    name: 'Caner Demir',
    position: 'partner',
    titleEn: 'Partner',
    titleTr: 'Ortak',
    email: 'cdemir@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400&h=400',
    practiceAreas: ['banking', 'ma', 'privatization', 'dispute'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'Boston University School of Law, LL.M. (1989)',
      'Dokuz Eylül Üniversitesi Hukuk Fakültesi, LL.B. (1985)',
      'Merrill High School, Wisconsin (1980)',
    ],
    bar: 'İstanbul Barosu',
  },
  {
    id: 205,
    slug: 'ayse-yilmaz',
    name: 'Ayşe Yılmaz',
    position: 'partner',
    titleEn: 'Partner',
    titleTr: 'Ortak',
    email: 'ayilmaz@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400&h=400',
    practiceAreas: ['dispute', 'competition', 'ip', 'it'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'İstanbul Üniversitesi, Sosyoloji (2018)',
      'İzmir Dokuz Eylül Üniversitesi Hukuk Fakültesi, LL.B. (1996)',
      'TED Lisesi, Zonguldak (1990)',
    ],
    bar: 'İstanbul Barosu',
  },
  {
    id: 215,
    slug: 'murat-kaya',
    name: 'Murat Kaya',
    position: 'partner',
    titleEn: 'Partner',
    titleTr: 'Ortak',
    email: 'mkaya@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400&h=400',
    practiceAreas: ['banking', 'capital-markets'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'İstanbul Üniversitesi Hukuk Fakültesi, LL.B. (2003)',
      'Anadolu Lisesi, Bursa (1999)',
    ],
    bar: 'İstanbul Barosu',
  },
  {
    id: 1240,
    slug: 'zeynep-celik',
    name: 'Zeynep Çelik',
    position: 'partner',
    titleEn: 'Partner',
    titleTr: 'Ortak',
    email: 'zcelik@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400&h=400',
    practiceAreas: ['ma', 'privatization', 'capital-markets', 'dispute', 'competition', 'foreign-investment'],
    languages: ['Türkçe', 'İngilizce', 'Hollandaca', 'Almanca'],
    education: [
      'İstanbul Üniversitesi, Özel Hukuk Doktora Adayı (2018)',
      'University of Cambridge, LL.M. (2017)',
      'Bilkent Üniversitesi, LL.B. (2016)',
      'TED Ankara Koleji (2012)',
      'Jan Arentsz CSG, Hollanda (2011)',
    ],
    bar: 'İstanbul Barosu',
  },
  {
    id: 1287,
    slug: 'bora-arslan',
    name: 'Bora Arslan',
    position: 'associate',
    titleEn: 'Associate',
    titleTr: 'Avukat',
    email: 'barslan@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=400&h=400',
    practiceAreas: ['banking', 'ma', 'capital-markets'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'Marmara Üniversitesi Hukuk Fakültesi, LL.B. (2021)',
      'Enka Okulları, Adapazarı (2016)',
    ],
    bar: 'İstanbul Barosu',
  },
  {
    id: 1295,
    slug: 'elif-yildiz',
    name: 'Elif Yıldız',
    position: 'associate',
    titleEn: 'Associate',
    titleTr: 'Avukat',
    email: 'eyildiz@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400&h=400',
    practiceAreas: ['dispute', 'ip'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'TOBB Ekonomi ve Teknoloji Üniversitesi Hukuk Fakültesi, LL.B. (2022)',
      'Karabük Anadolu Öğretmen Lisesi (2017)',
    ],
    bar: 'İstanbul Barosu',
  },
  {
    id: 1308,
    slug: 'deniz-ozturk',
    name: 'Deniz Öztürk',
    position: 'associate',
    titleEn: 'Associate',
    titleTr: 'Avukat',
    email: 'dozturk@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400&h=400',
    practiceAreas: ['banking', 'ma', 'capital-markets'],
    languages: ['İngilizce', 'Almanca', 'Türkçe'],
    education: [
      'İstanbul Bilgi Üniversitesi Hukuk Fakültesi, LL.B. (2023)',
      'Cağaloğlu Anadolu Lisesi (2018)',
    ],
    bar: 'İstanbul Barosu',
  },
  {
    id: 1309,
    slug: 'merve-bulut',
    name: 'Merve Bulut',
    position: 'associate',
    titleEn: 'Associate',
    titleTr: 'Avukat',
    email: 'mbulut@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=400&h=400',
    practiceAreas: ['banking', 'ma', 'capital-markets'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'Koç Üniversitesi Hukuk Fakültesi, LL.B. (2022)',
      'Tarsus Amerikan Koleji (2017)',
    ],
    bar: 'İstanbul Barosu',
  },
  {
    id: 1310,
    slug: 'kaan-koc',
    name: 'Kaan Koç',
    position: 'associate',
    titleEn: 'Associate',
    titleTr: 'Avukat',
    email: 'kkoc@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400&h=400',
    practiceAreas: ['banking', 'ma', 'capital-markets'],
    languages: ['Türkçe', 'Almanca', 'İngilizce'],
    education: [
      'Türk-Alman Üniversitesi Hukuk Fakültesi, LL.B. (2024)',
      'Çemberlitaş Anadolu Lisesi (2017)',
    ],
    bar: 'İstanbul Barosu',
  },
  {
    id: 1311,
    slug: 'selin-aydin',
    name: 'Selin Aydın',
    position: 'trainee',
    titleEn: 'Trainee',
    titleTr: 'Stajyer Avukat',
    email: 'saydin@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400&h=400',
    practiceAreas: ['banking', 'ma', 'capital-markets'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'TOBB Ekonomi ve Teknoloji Üniversitesi Hukuk Fakültesi, LL.B. (Beklenen 2026)',
      'TOBB Anadolu Lisesi (2018)',
    ],
    bar: null,
  },
  {
    id: 1313,
    slug: 'burak-guler',
    name: 'Burak Güler',
    position: 'trainee',
    titleEn: 'Trainee',
    titleTr: 'Stajyer Avukat',
    email: 'bguler@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400&h=400',
    practiceAreas: ['banking', 'ma', 'capital-markets'],
    languages: ['Türkçe', 'İngilizce', 'Almanca'],
    education: [
      'Koç Üniversitesi Hukuk Fakültesi, LL.B. (2025)',
      'Tarsus Amerikan Koleji (2021)',
      'SEV Tarsus (2016)',
    ],
    bar: null,
  },
  {
    id: 1317,
    slug: 'irem-cetin',
    name: 'İrem Çetin',
    position: 'trainee',
    titleEn: 'Trainee',
    titleTr: 'Stajyer Avukat',
    email: 'icetin@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=400&h=400',
    practiceAreas: ['banking', 'ma', 'capital-markets'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'İstanbul Üniversitesi, LL.B. (2024)',
      'TED Koleji, Kayseri (2020)',
    ],
    bar: null,
  },
  {
    id: 1318,
    slug: 'mete-aksoy',
    name: 'Mete Aksoy',
    position: 'trainee',
    titleEn: 'Trainee',
    titleTr: 'Stajyer Avukat',
    email: 'maksoy@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: 'https://images.unsplash.com/photo-1500048993953-d23a436266cf?auto=format&fit=crop&q=80&w=400&h=400',
    practiceAreas: ['dispute', 'ip'],
    languages: ['Türkçe', 'İngilizce'],
    education: [
      'Özyeğin Üniversitesi Hukuk Fakültesi, LL.B. (Beklenen 2025)',
      'Elazığ Final Akademi Lisesi (2021)',
    ],
    bar: null,
  },
  {
    id: 1319,
    slug: 'asli-yavuz',
    name: 'Aslı Yavuz',
    position: 'trainee',
    titleEn: 'Trainee',
    titleTr: 'Stajyer Avukat',
    email: 'ayavuz@werdy.av.tr',
    phone: '+90 212 324 96 34',
    image: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?auto=format&fit=crop&q=80&w=400&h=400',
    practiceAreas: ['banking', 'ma', 'capital-markets'],
    languages: ['Türkçe', 'İngilizce', 'Arapça'],
    education: [
      'Koç Üniversitesi Hukuk Fakültesi, LL.B. (2025)',
      'Tarsus Amerikan Koleji (2021)',
    ],
    bar: null,
  }
];
